### ISSUE TITLE
CONTENT - HOMEPAGE: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#10]

**Comment by jasonfyve** [comment]
These all run down the page in order from top to bottom

-Not seeing the H1 in the code. Needs to be "Fresh Baked Digital Marketing Agency in Columbus, Ohio"
-"We Deliver" needs to be an H2
-"Web Design & Digital Marketing That Delivers" needs to be an H2
-each of the business names under the portfolio section need to be H3s. (Fox Law Firm, Columbus Laser & Cataract etc.)
-"Sauce" in "The Secret Sauce" is spelled wrong
-In our phone number in the contact form, there should be a space between the area code and the first digit. Currently reads: (614)362-4480

**Comment by jakewelchert** [comment]
@jasonfyve Got all of these besides — each of the business names under the portfolio section need to be H3s. (Fox Law Firm, Columbus Laser & Cataract etc.) — will tweak this when we decide on the new approach for how those projects show up.

**Comment by jakewelchert** [comment]
Those business names are now H3's.
