### ISSUE TITLE
CONTENT - ABOUT US: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#11]

**Comment by jasonfyve** [comment]
-Make sure the H1 is "Digital Marketing Company Columbus Ohio"
-Make sure each person's name is an H3
-The logos for the Ohio Roots section are here (need to make them all white): https://drive.google.com/drive/folders/19bKdTLXJlqGn3BxJDtvzyqRYBqXICgbY?usp=sharing
-We no longer need the section "A Message From Our Digital Marketing Agency". The page can end with the recipe section and you can also get rid of the lightning bolt if it makes sense to do so.

**Comment by jakewelchert** [comment]
Updated for review. For the Ohio Roots logos...I'll need a better version of the Magnetic Springs logo. Vector if possible so I can turn it white.

**Comment by jasonfyve** [comment]
Try this client instead: Stevens Law Firm. I can't find the original for Magnetic Springs. Emailing you Stevens logo directly, looks like I can't upload SVG here

**Comment by jakewelchert** [comment]
Add logo and up for review.

**Comment by jasonfyve** [comment]
Looks perfect!

**Comment by jasonfyve** [comment]
Looks great! Only thing I noticed was that the "We're Legit" in the footer only pops out the logos on the homepage

**Comment by jakewelchert** [comment]
We're Legit issue moved to duplicate ticket.
