### ISSUE TITLE
CONTENT - SERVICES: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#12]

**Comment by jasonfyve** [comment]
-Make sure the H1 is "Digital Marketing Services Columbus Ohio"

**Comment by jakewelchert** [comment]
For some reason there was a copy change here. Not sure if it was me or if I pulled the current one from the Google Doc. Current headline is "We offer a full menu of 5 digital marketing services to help you achieve success". Do we need to change it to "Digital Marketing Services Columbus Ohio"?

**Comment by jasonfyve** [comment]
> For some reason there was a copy change here. Not sure if it was me or if I pulled the current one from the Google Doc. Current headline is "We offer a full menu of 5 digital marketing services to help you achieve success". Do we need to change it to "Digital Marketing Services Columbus Ohio"?

I want to keep that headline, but we do need the H1 text there somewhere. Maybe something like the badge we are doing for the individual service pages?

**Comment by jakewelchert** [comment]
Added and up for review.

**Comment by jasonfyve** [comment]
Closed duplicate. Looks good to go!

**Comment by jasonfyve** [comment]
The more that I think about it, I know that Caitlin is going to want to have the H1 text be the sans serif. Can we make that H1 one of the fonts we are using that is sans serif?

**Comment by jakewelchert** [comment]
![Screen Shot 2021-02-05 at 3 37 01 PM](https://user-images.githubusercontent.com/3301072/107091843-06cab480-67c8-11eb-96cc-8bde6b549b5a.png)

Are you talking about this one? If so, it's Avenir...it's just tracked out a bit for readability.

**Comment by jasonfyve** [comment]
Yeah! That looks great
