### ISSUE TITLE
CONTENT - OUR WORK: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#13]

**Comment by jasonfyve** [comment]
-Make sure the H1 in the code is "Our Work"

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Sent along some notes for some tweaks to the design/layout for this page as well as this section on the homepage. Let me know what you think or if it's something we can do.

**Comment by jakewelchert** [comment]
We can reconfigure this page...and the homepage but it's going to get pushed down the list since we currently have something in place. Maybe we touch base on this too.

**Comment by jakewelchert** [comment]
@jasonfyve The updated Our Work grid is pushed to the test site: https://fyvemarketing.frb.io/ourwork

Let me know how this is feeling and if you have any edits. Thanks!

**Comment by jasonfyve** [comment]
Lookin good!

**Comment by jakewelchert** [comment]
I updated this with some photos on the Our Work landing page. Also added on the homepage. If you're good with how this is looking I'll move on to the service pages and get the other version in there.

**Comment by jasonfyve** [comment]
Looks good! I think we already talked about it but it would be sweet to get some of the images designed sort of how that example site has them. Would make that section seem really polished.
![Screen Shot 2021-02-11 at 10 41 13 AM](https://user-images.githubusercontent.com/77985060/107668014-cd75c700-6c55-11eb-8f27-4e0e3b78f18c.png)

**Comment by jakewelchert** [comment]
@jasonfyve Yep! I'll get to images when we're through all the testing stuff.

**Comment by jakewelchert** [comment]
Closing since work images are in another ticket.
