### ISSUE TITLE
CONTENT - SERVICES - SEO: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#16]

**Comment by jakewelchert** [comment]
Content add/edited and up for review. Images are FPO (for placement only). We'll need to figure out what we want for these. Could be a similar style to the SEO page, or we could go with more of the lightning bolt/textured look.

**Comment by jasonfyve** [comment]
-add H1 badge
-Make each client name an H3 in the Our Work section
-Is it possible to make the name's of the people in the Fresh Feedback section H5's?
-Uploading the background pictures for the top sections in order.
![WhatIsSEO](https://user-images.githubusercontent.com/77985060/107076988-d7a94880-67b1-11eb-9369-b73e1e318e6a.jpg)
![WhyDoYouNeedSEO](https://user-images.githubusercontent.com/77985060/107077276-3a024900-67b2-11eb-849e-c984c34480f2.png)

**Comment by jakewelchert** [comment]
Up for review. Images added. H2's and H3's corrected. 

Moved Fresh Feedback comment to duplicate issue. Started new H1 badge issue.

**Comment by jasonfyve** [comment]
Looks perfect!
