### ISSUE TITLE
Homepage Review

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#22]
-The orange diamond in the hero doesn’t scale right. It gets mixed in with the logo in some sizes. Should it be closer to the circle pictures like in the Invision link? https://bit.ly/39pl3XL

-On my laptop screen, the “Fresh Baked…” part changes the number of lines it has based on the word rotating through. For instance, the "Squeezed" rotation puts it on 4 lines. Maybe we should reduce the font size so that it all fits tidy on the same amount of lines for all scrolling words?

-Can we make the pictures bigger in the Fresh Baked section and move them closer to the text? Closer to the original mockup. It's sort of floating out on its own.
![Screen Shot 2021-01-27 at 2 26 47 PM](https://user-images.githubusercontent.com/77985060/106049456-b9559580-60ab-11eb-9a70-c9c0bb5efccf.png)

-Weird character before “in” in the first sentence of the “We Deliver” paragraph

-change the font for “In Columbus, Ohio” under the hero and “We Deliver” in the second section (as seen in the original mockup.)

-The "Web Design & Digital Marketing that Delivers" section needs some work. I really like the format of the grid at the top here: https://make.studio/de/?ref=bestwebsite.gallery except for our hover could be black with white text. We can use all the current content we have for that section. Then still include the View More CTA that takes you to the corresponding portfolio page.

-Fresh Feedback section-the dot is scaling weird and is moving to weird places

**Comment by jasonfyve** [comment]
Mobile edits:

You probably have noticed most of them but I'll just post screenshots of what I'm seeing that needs to be tweaked.
![Screen Shot 2021-02-04 at 2 37 17 PM](https://user-images.githubusercontent.com/77985060/106952358-9ef86900-66f6-11eb-9bf3-b4b1632967f9.png)
![Screen Shot 2021-02-04 at 2 37 27 PM](https://user-images.githubusercontent.com/77985060/106952360-a15ac300-66f6-11eb-9830-61522ea0d856.png)
![Screen Shot 2021-02-04 at 2 37 45 PM](https://user-images.githubusercontent.com/77985060/106952362-a3248680-66f6-11eb-970b-8dc043d854f9.png)

**Comment by jakewelchert** [comment]
Yep, thanks for posting! I haven't pushed updates for this page yet. Should have something tomorrow.

**Comment by jakewelchert** [comment]
Pushed updates here...take another look at the homepage on mobile/tablet/desktop to review the above items and see if you see any other issues.

**Comment by jasonfyve** [comment]
There's only 2 things I noticed:

1. on mobile the "baked, poured, etc." is way off compared to the desktop version. Attached screenshot
2. The orange diamond in the header falls into the main menu when you are up in that section and click on the hamburger menu. Attached screenshot
![Image from iOS (1)](https://user-images.githubusercontent.com/77985060/107777299-3d448a00-6d08-11eb-89e3-d5dfcbf285a2.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/77985060/107777305-3fa6e400-6d08-11eb-9840-51f982353575.png)

**Comment by jakewelchert** [comment]
Thanks! For that first one, when you say way off compared to desktop are you talking about spacing or timing?

**Comment by jasonfyve** [comment]
The timing. Desktop version seems fine but on mobile it gets a little glitchy and seems like it gets way off.

**Comment by jakewelchert** [comment]
Got it! Thanks.

**Comment by jakewelchert** [comment]
@jasonfyve Fixed the orange block issue.

**Comment by jasonfyve** [comment]
Seeing this weird formatting on mobile now.
![IMG_0031](https://user-images.githubusercontent.com/77985060/108091890-c1b54680-7041-11eb-8170-3ed247246bff.PNG)

**Comment by jakewelchert** [comment]
Yep, this is the piece I emailed about. Had to rebuild it to fix the timing. Styles are updated and should look better now after a hard refresh.
