### ISSUE TITLE
Services Page Review

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#25]
-The whole top paragraph should be seen without needing to scroll (on desktop version-mobile looks good)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
> Updated for review.

Looks great! We will just need to change the website and SEO links to link them to the correct page and fit the H1 in there as mentioned in another ticket.

**Comment by jakewelchert** [comment]
Ah, great catch on the link. That's corrected. Will add that H1 in. Thanks!

**Comment by jakewelchert** [comment]
H1 added. Up for review.

**Comment by jasonfyve** [comment]
Perfect!
