### ISSUE TITLE
SERVICE PAGES - Add H1 badge

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#26]
Web Design - 
SEO -
Social Media - 
Google Ads - 
Content Marketing -

**Comment by jakewelchert** [comment]
Reconfigure where project examples show up on the page.

**Comment by jakewelchert** [comment]
@jasonfyve
- Badge graphics are in place but I still need to tweak the hidden H1 for each. Will do this and let you know when it's done.
- Layouts are also switched around so the work examples move up on the page.

**Comment by jasonfyve** [comment]
Is the social media one supposed to be on the SEO page? noticed the SEO one isn't right

**Comment by jakewelchert** [comment]
Ah, sorry bout that. Updated.

**Comment by jakewelchert** [comment]
Added some hover treatment to how those projects show up on the service pages. I'll work on image sizes so they're the same, but the functionality is there. How are you feeling about this?

https://fyvemarketing.frb.io/services/seo

**Comment by jasonfyve** [comment]
Looks dope!
