### ISSUE TITLE
Font Issue (Homepage & Services)

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#27]
Screenshots attached
![Screen Shot 2021-02-08 at 2 29 01 PM](https://user-images.githubusercontent.com/77985060/107282229-50154100-6a20-11eb-9153-3d137125c68a.png)
![Screen Shot 2021-02-08 at 2 28 57 PM](https://user-images.githubusercontent.com/77985060/107282233-50add780-6a20-11eb-88b2-ed804cae6e17.png)
![Screen Shot 2021-02-08 at 2 28 46 PM](https://user-images.githubusercontent.com/77985060/107282234-50add780-6a20-11eb-90df-424888c90a21.png)

**Comment by jakewelchert** [comment]
Ugh, yeah bro...that sucks.

**Comment by jakewelchert** [comment]
These should be updated. Can you check on your end for me?
