### ISSUE TITLE
Google Maps Issue

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#28]
Yo! Looking at the google maps URL, it needs to link here: https://www.google.com/maps/place//data=!4m2!3m1!1s0x88388f8af74b5db9:0x3093ab31749844b1?source=g.page.share

It looks like the current ones aren't linking there. I think the footer clickable address, navigation address, and contact form clickable address, and the contact page clickable address.

**Comment by jakewelchert** [comment]
Map link is updated. Take a look and let me know if I missed one.

**Comment by jasonfyve** [comment]
Good to go!
