### ISSUE TITLE
CONTACT FORM: Homepage and Contact page

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#29]
@jasonfyve I'll need to connect the contact forms on the Homepage and Contact page to something...do you have a preference or email service you'd like to look at. Or, I should be able to pull these into Craft and then you can export with a plugin.

**Comment by jasonfyve** [comment]
We use Google Business Suite for our email. Does that work?

**Comment by jakewelchert** [comment]
I'm thinking more like MailChimp or Hubspot. I think Caitlin said early on that you won't need something like Hubspot but I wondered if anything there had changed. Thanks!

**Comment by jasonfyve** [comment]
Ohhh. Nope! They can just go straight to her inbox.

**Comment by jakewelchert** [comment]
@jasonfyve We need a plugin to help confirm these emails are sent properly. Can you start an account for this service and get me credential info?

https://postmarkapp.com/

**Comment by jasonfyve** [comment]
i got u fam:

un: jasonfyve
pw: zw65yADDuFTkCa@

**Comment by jakewelchert** [comment]
This is resolved. I'll forward these emails to you when we do soft launch.
