### ISSUE TITLE
SITE WIDE: Clean up slide in navigation for different browser sizes

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#3]
Check on mobile and tablet

**Comment by jakewelchert** [comment]
-Can we have the phone icon and hamburger menu be sticky and scroll down the page?
-Is it possible to have something that says "Get In Touch" grouped with either the phone icon or the hamburger menu that appears when you get past the hero (clicking it takes you to the Contact page)?

**Comment by jakewelchert** [comment]
Added the sticky feature here and it's on the test site. There's some style tweaks for mobile and ipad but it feels pretty nice. Hides on scroll down and appears on scroll up.

Will revisit and add the 'Get In Touch' link

**Comment by jasonfyve** [comment]
Looks awesome!

**Comment by jakewelchert** [comment]
@jasonfyve Added some transitions to this along with the "Get in touch!" link. Let me know if that's what you were thinking.

**Comment by jasonfyve** [comment]
Is it possible to have it hid and only show up when the sticky menu is shown? I see on mobile it is that way. I really like the clean look of the hero. If not, no biggie, it looks great!

**Comment by jakewelchert** [comment]
Yep! Removed and updated.
