### ISSUE TITLE
Our Work/Portfolio Sections

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#35]
I figured this would be easier than breaking it up for each ticket created. [Here](https://drive.google.com/drive/folders/1I4ghZq3aQf4kT3Vxrm-30OvpgdgApHEc?usp=sharing) is the folder that has all the copy/testimonials/pictures/links for screenshots. The Homepage and Our Work page clients are in the same folder as labeled. Let me know if I provided enough.

Homepage "Our Work" Section-CHANGED 1 CLIENT (remove Fox Law Firm and replace with Ketron)
-fun designs like we talked about here: https://make.studio/de/?ref=bestwebsite.gallery
-Ketron Custom Builders
-Columbus Laser & Cataract Center
-Joseph Tree

Our Work Page (fun designs like we talked about here: https://make.studio/de/?ref=bestwebsite.gallery)
-Ketron
-Fox Law Firm
-McCloud Windows
-Columbus Laser
-The Timbrook Guesthouse
-Joseph Tree

Services Pages
-all content that's currently next to the thumbnails on the service pages are final-just need designed images for each
-only clients that should be linked to Our Work page are the Web Design examples-all other service pages should just be picture and description
-each service page has its own folder for images as labeled. Let me know if those images are what you're looking for.

**Comment by jakewelchert** [comment]
Awesome! Thanks for posting this. I'll get started on building project pages. Will probably work through one and send it for approval.

**Comment by jakewelchert** [comment]
I've got a few project pages going: https://fyvemarketing.frb.io/ourwork

Each one has a header image and I can continue to build out a few images for each page. Just wanted to run things past you before moving too far ahead. Let me know about any issues!

**Comment by jasonfyve** [comment]
Hell yeah! Love this direction

**Comment by jasonfyve** [comment]
<img width="589" alt="Screen Shot 2021-02-17 at 3 56 24 PM" src="https://user-images.githubusercontent.com/77985060/108273281-f22bdc00-7138-11eb-94ca-c212f0dd6a7f.png">
I'm sure it will be addressed but wanted to throw it out there that the one for Timbrook seems pretty pixelated.

**Comment by jakewelchert** [comment]
Good eye...its not looking great in the browser so I tried another mockup. Looking better now.

I also added more work images for review. I'll keep building these out.

**Comment by jasonfyve** [comment]
These are looking so good!

**Comment by jakewelchert** [comment]
How many images are you thinking for each? I think just the header isn't enough, but don't want to get too crazy. For instance,  what else would you like to see for this one: https://fyvemarketing.frb.io/ourwork/ketroncustombuilders

Maybe mobile mockups and then another large image?

**Comment by jakewelchert** [comment]
Same goes for this one: https://fyvemarketing.frb.io/ourwork/foxlawfirm

I could see some brand elements too. I know you did the website, but should we have the logo mocked up on some business cards/letterhead?

**Comment by jasonfyve** [comment]
Yeah! Putting the logo on business cards would be sweet. What do you think of adding some of the images I attached in those folders as stand-alone images mixed in with screenshots and logo designs? Maybe one of the sections could be a collage of cool images that we used on the site? Not sure how to show other stuff without it just being all screenshots from the website.

**Comment by jakewelchert** [comment]
**These have more photos that I worked on today:**
https://fyvemarketing.frb.io/ourwork/thetimbrookguesthouse
https://fyvemarketing.frb.io/ourwork/foxlawfirm
https://fyvemarketing.frb.io/ourwork/ketroncustombuilders

I can work on the other projects for the Our Work page tomorrow and then I feel good about doing a final cleanup for a 'soft launch'. We can get it on your live domain and start confirming SEO info is correct, as well as all links and images!

**Comment by jasonfyve** [comment]
Lookin good!

**Comment by jakewelchert** [comment]
Worked through more images today. They're all live in the Our Work projects.

Also, I'll need to prepare images for the projects that show up on the individual service pages. I'll use the images you provided and noted above. These should be:

- Prim Painting
- Go Geese Go
- Sea Ray of Cincinnati & Louisville
- Trailes West
- Champion Pest & Termite Control

**Comment by jasonfyve** [comment]
Yep! Just to make sure, those images won't link anywhere, correct? I think we had talked about not having those portfolio pages built yet and so we would only have the web design images link.

**Comment by jasonfyve** [comment]
Yep! Let me know if those images work. Some of them are ads that we used for campaigns that I was thinking could be photoshopped in a way to make them look cool like you did for web design stuff. Let me know if all the images I sent over are something you want to work with.

**Comment by jakewelchert** [comment]
So the ones that don't have a page built out aren't linked. Here's an example: https://fyvemarketing.frb.io/services/seo

Prim Painting doesn't link.

**Comment by jakewelchert** [comment]
Those images on the individual service pages are updated. Should have one for everything now. Let me know about changes.

**Comment by jakewelchert** [comment]
Those are updated now. Let me know about anything else and thanks!
