### ISSUE TITLE
Our Work Final Cleanup

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#38]
-should we hide the other categories in the dropdown for now until we add more portfolio work for all the other services?

-is the grid for the individual categories formatted yet? Screenshot of what the Web Design category looks like. 
![Screen Shot 2021-02-24 at 1 37 21 PM](https://user-images.githubusercontent.com/77985060/109055951-71735f80-76a5-11eb-8ff0-3cfeda0f6105.png)

**Comment by jakewelchert** [comment]
Good thought...and good catch. This is on my list to fix but haven't gotten to it. Will update.

**Comment by jakewelchert** [comment]
For this one...I'm tagging this as an enhancement. Since we're not launching with the category dropdown we're not really pushing people to this page. I can change later.
