### ISSUE TITLE
All Service Pages Final Cleanup

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#39]
-H1 badge gets cropped on mobile (see screenshot). This isn't a huge deal because it seems more of a stylistic thing so let me know if you like it better as-is.
![Image from iOS](https://user-images.githubusercontent.com/77985060/109055610-04f86080-76a5-11eb-9f6e-77d717de40d4.png)

-on mobile, the “View More” button/text is there for the work examples when it shouldn’t be (all the other services other than web design)

**Comment by jakewelchert** [comment]
I was going for a stylistic thing here...but I think it should be brought off the edge a bit. I'll update.

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jakewelchert** [comment]
How are you feeling about these updates?

**Comment by jasonfyve** [comment]
Looking good!
