### ISSUE TITLE
Web Design Service Page Final Cleanup

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#40]
-the hover treatments are formatting weird when in different browser sizes (see screenshot)
<img width="1140" alt="Screen Shot 2021-02-23 at 2 39 40 PM" src="https://user-images.githubusercontent.com/77985060/109056220-ca42f800-76a5-11eb-9cee-039157e844bf.png">

Stock Photos for FPO sections

-Built for Search Engines with Users in mind: 
https://www.shutterstock.com/image-photo/technology-concept-seo-1027893430 OR 
https://www.shutterstock.com/image-photo/searching-browsing-internet-data-information-networking-653127499 
 
-Taking Care of Updates: 
https://www.shutterstock.com/image-photo/taranto-italy-july-19-2019-young-1468294790

**Comment by jakewelchert** [comment]
The hover issue is based on text length. I can work up a solution for this. Also, can you purchase and download these images? Thanks!

**Comment by jasonfyve** [comment]
In order:

![shutterstock_1027893430](https://user-images.githubusercontent.com/77985060/109164146-b77d0180-773f-11eb-99a5-bb35c05e4d1b.png)

![shutterstock_1468294790](https://user-images.githubusercontent.com/77985060/109163589-1a21cd80-773f-11eb-84cd-b5f60bbfce0d.jpg)

**Comment by jakewelchert** [comment]
Images are updated for review.

**Comment by jasonfyve** [comment]
Perfect
