### ISSUE TITLE
About Us Page Final Cleanup

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#41]
-replace Stevens Law Firm with Columbus Laser & Cataract Center (logo file here: https://drive.google.com/file/d/12oiOv0KcIKYW616DV1I81dg2i_2zQ3BZ/view?usp=sharing). The logo we want to use for this is the one where the logo and text are on one line (text on the right side of the logo)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Perfect!
