### ISSUE TITLE
Social Media Service Page Final Cleanup

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#43]
Stock Photos for FPO sections

-What is in it for you?
https://www.shutterstock.com/image-photo/social-mediasocial-network-concept-smart-phone-730634437 OR https://www.shutterstock.com/image-photo/chiang-mai-thailand-mar-242019-man-1403200952
 
-Why is FYVE the best? 
https://www.shutterstock.com/image-vector/vector-realistic-isolated-neon-sign-five-1065494387 OR https://www.shutterstock.com/image-vector/five-3d-yellow-glowing-star-rating-1040843674

**Comment by jakewelchert** [comment]
Can you purchase and download these images? Thanks!

**Comment by jasonfyve** [comment]
In order:

![shutterstock_730634437](https://user-images.githubusercontent.com/77985060/109164630-4427bf80-7740-11eb-945d-5ac91c799338.jpg)

![shutterstock_1065494387](https://user-images.githubusercontent.com/77985060/109164636-468a1980-7740-11eb-8b74-bc994e555dde.jpg)

**Comment by jakewelchert** [comment]
Images are updated for review.

**Comment by jasonfyve** [comment]
Perfect
