### ISSUE TITLE
Mobile Formatting

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#45]
This might be a dumb question, but is this normal? (screenshot). When I mess with it on mobile it doesn't snap back into the normal formatting. 
![IMG_0063](https://user-images.githubusercontent.com/77985060/109162117-74ba2a00-773d-11eb-86d7-565e735f528d.PNG)

**Comment by jakewelchert** [comment]
What device are you seeing this on?

**Comment by jasonfyve** [comment]
I'm using my iphone. It normall shows when i switch to landscape mode and then switch back to normal mode, it doesn't snap back. Wasnt sure if that's just what happens or if its something we can fix.

**Comment by jakewelchert** [comment]
http://www.tzr.io/yarn-clip/d7b7db7f-6b77-438d-82b8-382dce8df18e/gif

**Comment by jasonfyve** [comment]
haha. emailing you the video because its too big for github

**Comment by jasonfyve** [comment]
Closing this. I noticed it does this for literally every website I visit.
