### ISSUE TITLE
Homepage Character Issue

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#46]
Seeing this on mobile:
![Screen Shot 2021-02-25 at 8 11 00 AM](https://user-images.githubusercontent.com/77985060/109165346-1000ce80-7741-11eb-9eb6-288d6f348ebf.png)

**Comment by jakewelchert** [comment]
I couldn't find this issue in the code so I deleted and added again. Can you check if it's fixed? Also, what device are you seeing this on?

**Comment by jasonfyve** [comment]
Fixed! Was only seeing it on desktop
