### ISSUE TITLE
SERVICE PAGES: Testimonial Block

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#48]
@jasonfyve I know the original content had different testimonials on each service page...are you still wanting this. Currently, they're all being pulled in but if for SEO purposes we need to only have a few that relate to each service page I can edit. Thanks!

**Comment by jasonfyve** [comment]
I think we should keep them how I had them because I tailored the review to match the service page it was on.

**Comment by jakewelchert** [comment]
Sounds good. I'll add the functionality.

**Comment by jakewelchert** [comment]
This is updated on each page in Craft.
