### ISSUE TITLE
SEO Service Page Update

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#52]
Can we replace Go Geese Go with Taneff Law? 
Blurb can be: We combine reputation management, content strategy, and keyword placement to keep Taneff Law positioned #1 in Google! Not only does his organic website traffic continue to climb, but the number of phone calls and website form submissions is up year-over-year. (Image is attached)
![Taneff Law2](https://user-images.githubusercontent.com/77985060/109558589-3a36f100-7a9f-11eb-87fa-2f31d2fa5e91.jpg)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Perfect
