### ISSUE TITLE
Web Design Service Page Update

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#53]
Since we are using regular photos for the other work examples on all the service pages, I think it would be a good idea to use a different photo for Timbrook on the Web Design page. Let's use this one:
![Timbrook-fullwidth-2_2021-02-22-195232](https://user-images.githubusercontent.com/77985060/109559048-d06b1700-7a9f-11eb-8f2f-e42d581a014f.jpg)

**Comment by jakewelchert** [comment]
These are pulled from the same place, so the Timbrook image will have to be this one or the other in Issue #52. Which one do you prefer?

**Comment by jasonfyve** [comment]
Hmm. Let's use this one!

**Comment by jakewelchert** [comment]
Thanks! Updated for review.

**Comment by jasonfyve** [comment]
Perfect
