### ISSUE TITLE
All Service Pages Update

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#56]
I got word that we need to add a contact form at the bottom of all our service pages. I'm thinking it can be something simple, and black so that it blends well with the bottom of the page (open to other ideas if you have them). It should be exactly like the homepage version, but we don't need a map (hoping that means it can be thinner and more streamlined). All the info should be the same and clickable just like the homepage one.

**Comment by jakewelchert** [comment]
This is added on each service page and up for review.

**Comment by jasonfyve** [comment]
Lookin good!

**Comment by jasonfyve** [comment]
What would it look like if we just used the contact form from the homepage? Would it clash with the design? It's a lot of black at the bottom the way it is now. Not sure what to do there.

**Comment by jakewelchert** [comment]
Updated for review. Both look good. Black is cool.

**Comment by jasonfyve** [comment]
Looks good!
