### ISSUE TITLE
Homepage Update

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#57]
I have received feedback about the main image of us on the homepage. When it fades in, because of the opacity, the black part of the section underneath is showing up when it first fades in (feedback is that it looks a little offputting-like the photo is cut in half by this black bar or something). Is there a way to change this?

**Comment by jakewelchert** [comment]
Good call. I updated how these are pulled in. Let me know if it feels better. Thanks!

**Comment by jasonfyve** [comment]
What if we had that entire black section below load in after the picture? It loads in 3 pieces now and feels a little disjointed. 
![Screen Shot 2021-03-02 at 2 40 22 PM](https://user-images.githubusercontent.com/77985060/109712566-cb709b00-7b65-11eb-899f-d06a66905065.png)

**Comment by jakewelchert** [comment]
Updated to pull that whole section up. Let me know if this is feeling better.

**Comment by jasonfyve** [comment]
This is it!
