### ISSUE TITLE
Homepage Update

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#58]
This might be out of scope, and we are totally fine exploring this option if it is, but is there something awesome we can do with our logo at the top of the homepage? It's the first thing you see and we want it to be as badass as possible. Maybe this is something we can chat about and see what we can come up with. If it's outside the scope we are open to figuring out a solution with you so that it can be as creative as possible!

**Comment by jakewelchert** [comment]
There are a few different ways to animate this logo. It's currently an image file, so there's not a ton we can do with it in a browser unless we make a few changes. I'd probably need the original art file for this. We could also have someone animate this and make it a video file which could be really cool. Have any ideas for what you're thinking or hoping?

**Comment by jasonfyve** [comment]
I'll get the AI file and we can circle back to this.
