### ISSUE TITLE
Navigation Logo Issue

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#59]
The logo is clashing with the navigation breakout when it's at the top of the page. See screenshot.
![Screen Shot 2021-03-02 at 2 59 16 PM](https://user-images.githubusercontent.com/77985060/109717228-63bd4e80-7b6b-11eb-8f28-a86c052bc62f.png)

**Comment by jasonfyve** [comment]
Also on the scroll up menu
![Screen Shot 2021-03-02 at 3 25 07 PM](https://user-images.githubusercontent.com/77985060/109717323-818ab380-7b6b-11eb-9e79-ed79ec40efbb.png)

**Comment by jakewelchert** [comment]
Is this on any particular page?

**Comment by jasonfyve** [comment]
I'm seeing it on every page except the homepage. Once you scroll past the header and then click the menu it isn't there, only when I'm at the top of the page.

**Comment by jakewelchert** [comment]
Great, thanks! I'll see what I can do to fix.

**Comment by jakewelchert** [comment]
This is updated for review.

**Comment by jasonfyve** [comment]
Sweet!
