### ISSUE TITLE
Portfolio Pages Tweak

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#60]
Let me know your thoughts on this:

We decided that we are only going to feature Web Design clients for our portfolio, so we don't really need the category dropdown or category pages, but we want the option to list the other services we do for those clients. Is it possible to keep the service categories on here, but have none of them link anywhere? I'm thinking on the backend we can tag the categories for each client, and have them listed, but not link to any category pages. 

For instance, we do social media and content for Timbrook, so we could have all of those services listed in pink on the portfolio page, but none of them click to any category pages.
<img width="372" alt="Screen Shot 2021-03-03 at 12 05 54 PM" src="https://user-images.githubusercontent.com/77985060/109851339-2fa06700-7c19-11eb-9e41-ded74d25dde6.png">

**Comment by jakewelchert** [comment]
I'll just remove the hyperlink for the text so the categories are pulled in with no link. I think we take to normal copy so people don't think it's a link.


![Screen Shot 2021-03-03 at 12 56 39 PM](https://user-images.githubusercontent.com/3301072/109857171-06370980-7c20-11eb-90aa-aa9e1963dac9.png)

**Comment by jakewelchert** [comment]
Or, do we link those services to the service page?

**Comment by jasonfyve** [comment]
Good call! I really like that idea. That way we can list a bunch of services there and show off those service pages.

**Comment by jakewelchert** [comment]
These now link to service pages.

**Comment by jasonfyve** [comment]
Awesome!
