### ISSUE TITLE
Ketron Portfolio Tweaks

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#62]
Everything looks great! Just need to clean up a couple of things before launch:

Need to change a couple of the photoshopped items. If the photos I attach here aren't high-res enough please let me know

-screenshot of the phone next to the laptop needs to be taken from this screen
![mobile next to laptop](https://user-images.githubusercontent.com/77985060/110005401-0b5a8e00-7cde-11eb-908e-44df0fc87638.png)

-in the row of 3 phones, the screenshots should be from these screens (in order)
![mobile1](https://user-images.githubusercontent.com/77985060/110005866-9045a780-7cde-11eb-8504-67fe0462d4de.PNG)
![mobile2](https://user-images.githubusercontent.com/77985060/110005878-93409800-7cde-11eb-945d-e326f8824e91.PNG)
![mobile3](https://user-images.githubusercontent.com/77985060/110005886-95a2f200-7cde-11eb-8715-3b4db4a2c627.PNG)

Services to tag:
Website Design & Development 
Content & Email Marketing 
Social Media Management

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Perfect
