### ISSUE TITLE
Columbus Laser Portfolio Tweaks

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#63]
For the section with 3 phones, please replace the first 2 photoshopped screenshots with these 2 (in order)

![Mobile1](https://user-images.githubusercontent.com/77985060/110006427-45785f80-7cdf-11eb-8e5b-65cdc65aa94b.png)
![Mobile2](https://user-images.githubusercontent.com/77985060/110006441-49a47d00-7cdf-11eb-8fe3-a9c1457598cd.png)

Services Tagged:
Web Design & Development
SEO
Google Ads Management
Social Media Management

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Perfect!
