### ISSUE TITLE
Fox Law Firm Portfolio Tweaks

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#64]
For the photoshopped screenshot on the phone next to the laptop, please use this page screenshot:
![mobile image next to laptop](https://user-images.githubusercontent.com/77985060/110006710-9720ea00-7cdf-11eb-824f-6aada2d91a8d.png)

For the section with 3 phones, please replace the 1st screenshot and the 3rd screenshot with these (in order)
![Mobile image 1](https://user-images.githubusercontent.com/77985060/110006840-b750a900-7cdf-11eb-98c8-2edabab1b5c0.png)
![mobile image 3](https://user-images.githubusercontent.com/77985060/110006847-b9b30300-7cdf-11eb-8839-423ec975227d.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Awesome!

**Comment by jasonfyve** [comment]
Wait crap. We didnt do social media for him. Not sure where that's pulling from.

**Comment by jakewelchert** [comment]
Updated.

**Comment by jasonfyve** [comment]
Awesome. I assume this is something I can easily do on the backend so I can go in and tweak those later so I won't create new tickets for that.
