### ISSUE TITLE
Timbrook Guesthouse Portfolio Tweaks

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#65]
For the section with 3 phones, please replace the 1st and 2nd photoshop screenshots with these (in order):
![mobile1](https://user-images.githubusercontent.com/77985060/110007203-0f87ab00-7ce0-11eb-811b-aeefe53521d6.png)
![mobile2](https://user-images.githubusercontent.com/77985060/110007218-144c5f00-7ce0-11eb-9f64-6cb1c4eded7a.png)

Replace the picture at the bottom of the house and pool with this picture:
![replace house pic at bottom of page](https://user-images.githubusercontent.com/77985060/110007314-262e0200-7ce0-11eb-93e4-5cff6396ee52.jpg)

Services Tagged:
Website Design & Development 
Content & Email Marketing
SEO
Google Ads
Social Media Management

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jasonfyve** [comment]
Great!
