### ISSUE TITLE
Icon Spacing on Menu

### ISSUE THREAD

**Issue by jasonfyve** [jakewelchert/fyve#66]
Just a quick tweak on the desktop menu (mobile looks good)-icons seem really close together
![Screen Shot 2021-03-04 at 9 04 50 AM](https://user-images.githubusercontent.com/77985060/110037314-d82af580-7d03-11eb-81e5-c980396beb43.png)

**Comment by jakewelchert** [comment]
Yeah, I’m still working through the nav stuff so I’ll let you know when it’s all good to review. Thanks!

_______

Jake Welchert

e - jakewelchert@gmail.com
p - 402-980-5368

**Comment by jakewelchert** [comment]
Updated for review.
