### ISSUE TITLE
SITE WIDE: Add social media links to icons in navigation

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#8]
Need to look up links

**Comment by jakewelchert** [comment]
@jasonfyve I have Twitter as one of the icons. Does FYVE have Twitter or should it be LinkedIn?

**Comment by jasonfyve** [comment]
It should be LinkedIn. We don't have Twitter at this time. Here's our URL: https://www.linkedin.com/company/fyve-marketing

**Comment by jakewelchert** [comment]
Added LinkedIn icon and link in navigation.

**Comment by jakewelchert** [comment]
Resolved.
