### ISSUE TITLE
SITE WIDE: Certification logos in footer

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#9]
Need to add these

**Comment by jakewelchert** [comment]
-Change text to "We're Legit"
-Created a folder for the logos we want to be included. They should probably all be white, correct? https://drive.google.com/drive/folders/1aG_uk2HvOvHgYJPC-0wyI9OYG3HcspYv?usp=sharing

**Comment by jakewelchert** [comment]
Only showing on Homepage

**Comment by jakewelchert** [comment]
@jasonfyve Updated so this is showing on every page. Take a look and let me know how it's working for you.

**Comment by jasonfyve** [comment]
Looks perfect!
